BlockStates -down-> Fault : Error
BlockStates -down-> Disabling : Disable

Disabling -left-> Fault : Error
Disabling -right-> Disabled

state Fault <<Fault>>
Fault : End state

state Disabled <<Disabled>>
Disabled : End state