NormalStates --> Aborting : Abort
NormalStates --> Fault : Error
NormalStates --> Disabling : Disable
Disabling --> Disabled
Disabling -left-> Fault : Error

Aborting -left-> Aborted
Aborting -right-> Fault : Error

state Aborted <<Abort>>
Aborted : End state

state Fault <<Fault>>
Fault : End state

state Disabled <<Disabled>>
Disabled : End state
