skinparam handwritten true

skinparam state {
  BackgroundColor #99CFCF
  BackgroundColor<<Rest>> #AAE7AA
  BackgroundColor<<Abort>> #FFBE89
  BackgroundColor<<Fault>> #F03232
  BackgroundColor<<Disabled>> #AAAAAA
  BorderColor Gray
  ArrowColor Black
  FontSize 14
  FontStyle bold
  ArrowFontSize 12
  AttributeFontSize 12
}

skinparam backgroundColor transparent
