skinparam handwritten true

skinparam defaultFontName Humor Sans

skinparam frame {
  FontSize 14
  FontStyle plain
}

skinparam component {
  FontSize 12
}

skinparam state {
  BackgroundColor #BEE1E1
  BackgroundColor<<Rest>> #BBE7BB
  BackgroundColor<<Abort>> #FFBE89
  BackgroundColor<<Fault>> #F03232
  BackgroundColor<<InactiVe>> #AAAAAA
  BorderColor Gray
  ArrowColor Black
  FontSize 14
  ArrowFontSize 12
  AttributeFontSize 12
}

skinparam backgroundColor transparent
